/** Avatars progression : 1 / étape, hors avatars par défaut, du plus simple au plus iconique. */
export const PROGRESSION_AVATARS = [
  { stage: 1, url: '/images/nintendo/characters/toad.png', label: 'Toad' },
  { stage: 2, url: '/images/nintendo/characters/bowser-junior.png', label: 'Bowser Junior' },
  { stage: 3, url: '/images/nintendo/characters/rondoudou.png', label: 'Rondoudou' },
  { stage: 4, url: '/images/sega/characters/zombie-the-house-of-the-dead.png', label: 'Zombie' },
  { stage: 5, url: '/images/sega/characters/chupea.png', label: 'Chupea' },
  { stage: 6, url: '/images/sega/characters/chuih.png', label: 'Chuih' },
  { stage: 7, url: '/images/sega/characters/AiAi.png', label: 'AiAi' },
  { stage: 8, url: '/images/sega/characters/gus.png', label: 'Gus' },
  { stage: 9, url: '/images/sega/characters/mew-mew.png', label: 'Mew Mew' },
  { stage: 10, url: '/images/sega/characters/axel.png', label: 'Axel' },
  { stage: 11, url: '/images/xbox/characters/shu.png', label: 'Shu' },
  { stage: 12, url: '/images/xbox/characters/pirate.png', label: 'Pirate' },
  { stage: 13, url: '/images/xbox/characters/viva-pinata.png', label: 'Viva Piñata' },
  { stage: 14, url: '/images/nintendo/characters/ludwig-von-koopa.png', label: 'Ludwig von Koopa' },
  { stage: 15, url: '/images/nintendo/characters/lemmy-koopa.png', label: 'Lemmy Koopa' },
  { stage: 16, url: '/images/nintendo/characters/iggy-koopa.png', label: 'Iggy Koopa' },
  { stage: 17, url: '/images/nintendo/characters/wendy-o-koopa.png', label: 'Wendy O. Koopa' },
  { stage: 18, url: '/images/nintendo/characters/morton-koopa-jr.png', label: 'Morton Koopa Jr.' },
  { stage: 19, url: '/images/playstation/characters/daxter.png', label: 'Daxter' },
  { stage: 20, url: '/images/nintendo/characters/wii-fit-trainer.png', label: 'Wii Fit Trainer' },
  { stage: 21, url: '/images/nintendo/characters/helix.png', label: 'Helix' },
  { stage: 22, url: '/images/nintendo/characters/duo-duck-hunt.png', label: 'Duo Duck Hunt' },
  { stage: 23, url: '/images/nintendo/characters/roy.png', label: 'Roy' },
  { stage: 24, url: '/images/nintendo/characters/little-mac.png', label: 'Little Mac' },
  { stage: 25, url: '/images/nintendo/characters/ribbon-girl.png', label: 'Ribbon Girl' },
  { stage: 26, url: '/images/nintendo/characters/springman.png', label: 'Spring Man' },
  { stage: 27, url: '/images/nintendo/characters/ice-climbers.png', label: 'Ice Climbers' },
  { stage: 28, url: '/images/sega/characters/ryo.png', label: 'Ryo' },
  { stage: 29, url: '/images/sega/characters/joe-musashi.png', label: 'Joe Musashi' },
  { stage: 30, url: '/images/sega/characters/pilote-hang-on.png', label: 'Pilote Hang-On' },
  { stage: 31, url: '/images/sega/characters/le-joueur.png', label: 'Le Joueur' },
  { stage: 32, url: '/images/sega/characters/billy-hatcher.png', label: 'Billy Hatcher' },
  { stage: 33, url: '/images/nintendo/characters/ayo-et-oli.png', label: 'Ayo et Oli' },
  { stage: 34, url: '/images/nintendo/characters/ness.png', label: 'Ness' },
  { stage: 35, url: '/images/nintendo/characters/lucas.png', label: 'Lucas' },
  { stage: 36, url: '/images/nintendo/characters/tom-nook.png', label: 'Tom Nook' },
  { stage: 37, url: '/images/playstation/characters/parappa-the-rapper.png', label: 'Parappa' },
  { stage: 38, url: '/images/sega/characters/amigo.png', label: 'Amigo' },
  { stage: 39, url: '/images/sega/characters/dj-professeur-k.png', label: 'DJ Professeur K' },
  { stage: 40, url: '/images/sega/characters/b.-d.-joe.png', label: 'B.D. Joe' },
  { stage: 41, url: '/images/sega/characters/taro-sega-boy.png', label: 'Taro Sega Boy' },
  { stage: 42, url: '/images/sega/characters/taro-sega-girl.png', label: 'Taro Sega Girl' },
  { stage: 43, url: '/images/sega/characters/alberto.png', label: 'Alberto' },
  { stage: 44, url: '/images/nintendo/characters/sheik.png', label: 'Sheik' },
  { stage: 45, url: '/images/playstation/characters/sackboy.png', label: 'Sackboy' },
  { stage: 46, url: '/images/xbox/characters/joule-adams.png', label: 'Joule Adams' },
  { stage: 47, url: '/images/xbox/characters/vela.png', label: 'Vela' },
  { stage: 48, url: '/images/nintendo/characters/peppy-hare.png', label: 'Peppy Hare' },
  { stage: 49, url: '/images/nintendo/characters/fille-inkling.png', label: 'Fille Inkling' },
  { stage: 50, url: '/images/xbox/characters/juno.png', label: 'Juno' },
  { stage: 51, url: '/images/xbox/characters/ori.png', label: 'Ori' },
  { stage: 52, url: '/images/xbox/characters/steeve.png', label: 'Steeve' },
  { stage: 53, url: '/images/xbox/characters/cooper.png', label: 'Cooper' },
  { stage: 54, url: '/images/xbox/characters/moine.png', label: 'Moine' },
  { stage: 55, url: '/images/xbox/characters/jd-fenix.png', label: 'JD Fenix' },
  { stage: 56, url: '/images/xbox/characters/jago.png', label: 'Jago' },
  { stage: 57, url: '/images/nintendo/characters/roi-dadidou.png', label: 'Roi Dadidou' },
  { stage: 58, url: '/images/nintendo/characters/general-pepper.png', label: 'General Pepper' },
  { stage: 59, url: '/images/playstation/characters/kat.png', label: 'Kat' },
  { stage: 60, url: '/images/sega/characters/adam-hunter.png', label: 'Adam Hunter' },
  { stage: 61, url: '/images/sega/characters/death-adder.png', label: 'Death Adder' },
  { stage: 62, url: '/images/sega/characters/gilius-thunderhead.png', label: 'Gilius Thunderhead' },
  { stage: 63, url: '/images/nintendo/characters/hero-ring-fit-adventure.png', label: 'Héros Ring Fit' },
  { stage: 64, url: '/images/nintendo/characters/waluigi.png', label: 'Waluigi' },
  { stage: 65, url: '/images/nintendo/characters/pit.png', label: 'Pit' },
  { stage: 66, url: '/images/nintendo/characters/marth.png', label: 'Marth' },
  { stage: 67, url: '/images/nintendo/characters/wario.png', label: 'Wario' },
  { stage: 68, url: '/images/xbox/characters/hornet.png', label: 'Hornet' },
  { stage: 69, url: '/images/nintendo/characters/lyn.png', label: 'Lyn' },
  { stage: 70, url: '/images/nintendo/characters/marie.png', label: 'Marie' },
  { stage: 71, url: '/images/nintendo/characters/perle-et-coralie.png', label: 'Perle et Coralie' },
  { stage: 72, url: '/images/nintendo/characters/krystal.png', label: 'Krystal' },
  { stage: 73, url: '/images/sega/characters/blaze-fielding.png', label: 'Blaze Fielding' },
  { stage: 74, url: '/images/sega/characters/aika.png', label: 'Aika' },
  { stage: 75, url: '/images/sega/characters/la-fille.png', label: 'La Fille' },
  { stage: 76, url: '/images/sega/characters/tyris-flare.png', label: 'Tyris Flare' },
  { stage: 77, url: '/images/sega/characters/gena.png', label: 'Gena' },
  { stage: 78, url: '/images/nintendo/characters/wolf-o-donnell.png', label: 'Wolf O\'Donnell' },
  { stage: 79, url: '/images/nintendo/characters/lucina.png', label: 'Lucina' },
  { stage: 80, url: '/images/nintendo/characters/ike.png', label: 'Ike' },
  { stage: 81, url: '/images/xbox/characters/reaver.png', label: 'Reaver' },
  { stage: 82, url: '/images/xbox/characters/senua.png', label: 'Senua' },
  { stage: 83, url: '/images/playstation/characters/nathan-drake.png', label: 'Nathan Drake' },
  { stage: 84, url: '/images/nintendo/characters/captain-falcon.png', label: 'Captain Falcon' },
  { stage: 85, url: '/images/nintendo/characters/ridley.png', label: 'Ridley' },
  { stage: 86, url: '/images/playstation/characters/aloy.png', label: 'Aloy' },
  { stage: 87, url: '/images/xbox/characters/cortana.png', label: 'Cortana' },
  { stage: 88, url: '/images/nintendo/characters/samus-sans-armure.png', label: 'Samus sans armure' },
  { stage: 89, url: '/images/sega/characters/hatsune-miku.png', label: 'Hatsune Miku' },
  { stage: 90, url: '/images/nintendo/characters/palutena.png', label: 'Palutena' },
  { stage: 91, url: '/images/xbox/characters/banjo-et-kazooie.png', label: 'Banjo & Kazooie' },
  { stage: 92, url: '/images/playstation/characters/jak.png', label: 'Jak' },
  { stage: 93, url: '/images/sega/characters/ulala.png', label: 'Ulala' },
  { stage: 94, url: '/images/sega/characters/ecco-the-dolphin.png', label: 'Ecco the Dolphin' },
  { stage: 95, url: '/images/xbox/characters/spyro.png', label: 'Spyro' },
  { stage: 96, url: '/images/xbox/characters/joanna-dark.png', label: 'Joanna Dark' },
  { stage: 97, url: '/images/xbox/characters/general-raam.png', label: 'General Raam' },
  { stage: 98, url: '/images/nintendo/characters/bayonetta.png', label: 'Bayonetta' },
  { stage: 99, url: '/images/nintendo/characters/mewtwo.png', label: 'Mewtwo' },
] as const;

export type ProgressionAvatar = (typeof PROGRESSION_AVATARS)[number];

export function progressionAvatarForStage(stage: number) {
  const s = Math.max(1, Math.min(99, Math.floor(stage)));
  return PROGRESSION_AVATARS[s - 1];
}

export function allProgressionAvatarUrls(): string[] {
  return PROGRESSION_AVATARS.map((a) => a.url);
}
